// <auto-generated />
using System;
using LiotecnicaHub.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiotecnicaHub.Web.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260618150253_AddUserApplicationAccessFase3")]
    partial class AddUserApplicationAccessFase3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubAccessAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AffectedUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewData")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousData")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("HubAccessAudits", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubAccessScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ExternalCode");

                    b.ToTable("HubAccessScopes", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("HubAdmins", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LaunchUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.HasIndex("SystemId");

                    b.ToTable("HubApplications", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubApplicationAccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HubApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HubApplicationId");

                    b.ToTable("HubApplicationAccessRules", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubEntraConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallbackPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecretProtected")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HubBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HubEntraConfigs", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.HasIndex("SystemId");

                    b.ToTable("HubPermissions", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HubProfiles", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubProfilePermission", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("HubProfilePermissions", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubProfileSystemAccess", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "SystemId");

                    b.HasIndex("SystemId");

                    b.ToTable("HubProfileSystemAccesses", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HubSystems", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubSystemModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemId", "Code")
                        .IsUnique();

                    b.ToTable("HubSystemModules", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("HubUsers", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUserApplicationAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("HubUserApplicationAccesses", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("HubUserProfiles", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUserProfileScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ScopeId");

                    b.HasIndex("UserId");

                    b.ToTable("HubUserProfileScopes", (string)null);
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubApplication", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubSystem", "System")
                        .WithMany("Applications")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("System");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubApplicationAccessRule", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubApplication", "Application")
                        .WithMany("AccessRules")
                        .HasForeignKey("HubApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubPermission", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubSystemModule", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubSystem", "System")
                        .WithMany("Permissions")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("System");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubProfilePermission", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubPermission", "Permission")
                        .WithMany("ProfilePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubProfile", "Profile")
                        .WithMany("ProfilePermissions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubProfileSystemAccess", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubProfile", "Profile")
                        .WithMany("ProfileSystemAccesses")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubSystem", "System")
                        .WithMany("ProfileSystemAccesses")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("System");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubSystemModule", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubSystem", "System")
                        .WithMany("Modules")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUserApplicationAccess", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubApplication", "Application")
                        .WithMany("UserApplicationAccesses")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubUser", "User")
                        .WithMany("UserApplicationAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUserProfile", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubProfile", "Profile")
                        .WithMany("UserProfiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubUser", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUserProfileScope", b =>
                {
                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubProfile", "Profile")
                        .WithMany("UserProfileScopes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubAccessScope", "Scope")
                        .WithMany("UserProfileScopes")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiotecnicaHub.Web.Domain.Entities.HubUser", "User")
                        .WithMany("UserProfileScopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Scope");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubAccessScope", b =>
                {
                    b.Navigation("UserProfileScopes");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubApplication", b =>
                {
                    b.Navigation("AccessRules");

                    b.Navigation("UserApplicationAccesses");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubPermission", b =>
                {
                    b.Navigation("ProfilePermissions");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubProfile", b =>
                {
                    b.Navigation("ProfilePermissions");

                    b.Navigation("ProfileSystemAccesses");

                    b.Navigation("UserProfileScopes");

                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubSystem", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Modules");

                    b.Navigation("Permissions");

                    b.Navigation("ProfileSystemAccesses");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubSystemModule", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("LiotecnicaHub.Web.Domain.Entities.HubUser", b =>
                {
                    b.Navigation("UserApplicationAccesses");

                    b.Navigation("UserProfileScopes");

                    b.Navigation("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
