// <auto-generated />
using LiotecnicaHub.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LiotecnicaHub.Web.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260619120000_AddHubUserPasswordHash")]
    partial class AddHubUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model registrado no HubDbContextModelSnapshot após migrations subsequentes.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
#pragma warning restore 612, 618
        }
    }
}
