-- Validação local da consulta admin requisições RM (espelha RmRequisicoesQueries.cs).
-- Parâmetros: mesmos defaults da tela (3 meses, status 1 e 3).
SET NOCOUNT ON;

DECLARE @Tipo NVARCHAR(80) = NULL;
DECLARE @DataDe DATE = '$(DataDe)';
DECLARE @DataAte DATE = '$(DataAte)';
DECLARE @CodStatusCsv VARCHAR(200) = ',1,3,';
DECLARE @SearchPattern NVARCHAR(4000) = NULL;
DECLARE @Offset INT = 0;
DECLARE @PageSize INT = 20;

PRINT '=== validate-rm-requisicoes ===';
PRINT CONCAT('Periodo: ', CONVERT(varchar(10), @DataDe, 120), ' .. ', CONVERT(varchar(10), @DataAte, 120));
PRINT CONCAT('CodStatusCsv: ', @CodStatusCsv);

DECLARE @t0 datetime2 = SYSDATETIME();

WITH REQUISICOES AS
(
    SELECT
        'AUMENTO_QUADRO' AS TIPO_REQUISICAO,
        R.CODCOLREQUISICAO,
        R.IDREQ,
        R.JUSTIFICATIVA,
        R.DATAABERTURA,
        R.DATAPREVISTA,
        R.DATACONCLUSAO,
        R.DATACANCELAMENTO,
        R.CODSTATUS,
        R.CODCOLREQUISITANTE,
        R.CHAPAREQUISITANTE,
        R.CODATENDIMENTO,
        R.CODLOCAL,
        CAST(NULL AS VARCHAR(20)) AS TIPOREQPAI,
        CAST(NULL AS INT) AS IDREQPAI,
        CAST(NULL AS VARCHAR(30)) AS CHAPA_FUNCIONARIO,
        CAST(NULL AS VARCHAR(30)) AS CHAPA_SUBSTITUTO,
        R.NUMVAGAS,
        R.CODFILIAL,
        R.CODSECAO,
        R.CODFUNCAO,
        R.VLRSALARIO,
        R.CODCCUSTO,
        R.RECCREATEDBY,
        R.RECCREATEDON,
        R.RECMODIFIEDBY,
        R.RECMODIFIEDON
    FROM VREQAUMENTOQUADRO R
        WHERE (@Tipo IS NULL OR @Tipo = 'AUMENTO_QUADRO')
        AND (@DataDe IS NULL OR R.DATAABERTURA >= @DataDe)
        AND (@DataAte IS NULL OR R.DATAABERTURA < DATEADD(day, 1, @DataAte))
        AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(R.CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
        AND (@SearchPattern IS NULL OR (CAST(R.IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR R.JUSTIFICATIVA LIKE @SearchPattern))
    UNION ALL
    SELECT
        'SUBSTITUICAO',
        R.CODCOLREQUISICAO,
        R.IDREQ,
        R.JUSTIFICATIVA,
        R.DATAABERTURA,
        R.DATAPREVISTA,
        R.DATACONCLUSAO,
        R.DATACANCELAMENTO,
        R.CODSTATUS,
        R.CODCOLREQUISITANTE,
        R.CHAPAREQUISITANTE,
        R.CODATENDIMENTO,
        R.CODLOCAL,
        R.TIPOREQPAI,
        R.IDREQPAI,
        CAST(NULL AS VARCHAR(30)),
        R.CHAPASUBSTITUTO,
        CAST(NULL AS INT),
        R.CODFILIAL,
        R.CODSECAO,
        R.CODFUNCAO,
        R.VLRSALARIO,
        R.CODCCUSTO,
        R.RECCREATEDBY,
        R.RECCREATEDON,
        R.RECMODIFIEDBY,
        R.RECMODIFIEDON
    FROM VREQSUBSTITUICAO R
        WHERE (@Tipo IS NULL OR @Tipo = 'SUBSTITUICAO')
        AND (@DataDe IS NULL OR R.DATAABERTURA >= @DataDe)
        AND (@DataAte IS NULL OR R.DATAABERTURA < DATEADD(day, 1, @DataAte))
        AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(R.CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
        AND (@SearchPattern IS NULL OR (CAST(R.IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR R.JUSTIFICATIVA LIKE @SearchPattern))
    UNION ALL
    SELECT
        'DESLIGAMENTO',
        R.CODCOLREQUISICAO,
        R.IDREQ,
        R.JUSTIFICATIVA,
        R.DATAABERTURA,
        R.DATAPREVISTA,
        R.DATACONCLUSAO,
        R.DATACANCELAMENTO,
        R.CODSTATUS,
        R.CODCOLREQUISITANTE,
        R.CHAPAREQUISITANTE,
        R.CODATENDIMENTO,
        R.CODLOCAL,
        CAST(NULL AS VARCHAR(20)),
        CAST(NULL AS INT),
        R.CHAPA,
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS INT),
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS DECIMAL(18,2)),
        R.CODCCUSTO,
        R.RECCREATEDBY,
        R.RECCREATEDON,
        R.RECMODIFIEDBY,
        R.RECMODIFIEDON
    FROM VREQDESLIGAMENTO R
        WHERE (@Tipo IS NULL OR @Tipo = 'DESLIGAMENTO')
        AND (@DataDe IS NULL OR R.DATAABERTURA >= @DataDe)
        AND (@DataAte IS NULL OR R.DATAABERTURA < DATEADD(day, 1, @DataAte))
        AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(R.CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
        AND (@SearchPattern IS NULL OR (CAST(R.IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR R.JUSTIFICATIVA LIKE @SearchPattern))
),
Base AS (
    SELECT
        Q.TIPO_REQUISICAO,
        Q.CODCOLREQUISICAO,
        Q.IDREQ,
        Q.JUSTIFICATIVA,
        Q.DATAABERTURA,
        Q.DATAPREVISTA,
        Q.DATACONCLUSAO,
        Q.DATACANCELAMENTO,
        Q.CODSTATUS,
        S.DESCRICAO AS STATUS_DESCRICAO,
        S.PODEALTERAR AS STATUS_PERMITE_ALTERAR,
        Q.CODCOLREQUISITANTE,
        Q.CHAPAREQUISITANTE,
        FREQ.NOME AS NOME_REQUISITANTE,
        Q.CODATENDIMENTO,
        Q.CODLOCAL,
        HEXT.ASSUNTOOC AS ATENDIMENTO_ASSUNTO,
        Q.TIPOREQPAI,
        Q.IDREQPAI,
        Q.CHAPA_FUNCIONARIO,
        FFUNC.NOME AS NOME_FUNCIONARIO_ENVOLVIDO,
        Q.CHAPA_SUBSTITUTO,
        FSUB.NOME AS NOME_FUNCIONARIO_SUBSTITUTO,
        Q.NUMVAGAS,
        Q.CODFILIAL,
        Q.CODSECAO,
        Q.CODFUNCAO,
        FUN.NOME AS NOME_FUNCAO,
        FUN.DESCRICAO AS DESCRICAO_FUNCAO,
        Q.VLRSALARIO,
        Q.CODCCUSTO,
        Q.RECCREATEDBY,
        Q.RECCREATEDON,
        Q.RECMODIFIEDBY,
        Q.RECMODIFIEDON
    FROM REQUISICOES Q
    LEFT JOIN VREQSTATUS S ON S.CODINTERNO = Q.CODSTATUS
    LEFT JOIN PFUNC FREQ ON FREQ.CODCOLIGADA = Q.CODCOLREQUISITANTE AND FREQ.CHAPA = Q.CHAPAREQUISITANTE
    LEFT JOIN PFUNC FFUNC ON FFUNC.CODCOLIGADA = Q.CODCOLREQUISICAO AND FFUNC.CHAPA = Q.CHAPA_FUNCIONARIO
    LEFT JOIN PFUNC FSUB ON FSUB.CODCOLIGADA = Q.CODCOLREQUISICAO AND FSUB.CHAPA = Q.CHAPA_SUBSTITUTO
    LEFT JOIN PFUNCAO FUN ON FUN.CODCOLIGADA = Q.CODCOLREQUISICAO AND FUN.CODIGO = Q.CODFUNCAO
    LEFT JOIN HATENDIMENTOBASE HEXT ON HEXT.CODCOLIGADA = Q.CODCOLREQUISICAO AND HEXT.CODLOCAL = Q.CODLOCAL AND HEXT.CODATENDIMENTO = Q.CODATENDIMENTO
)
SELECT COUNT(1) AS TotalCount FROM Base
WHERE
    (@Tipo IS NULL OR TIPO_REQUISICAO = @Tipo)
    AND (@DataDe IS NULL OR DATAABERTURA >= @DataDe)
    AND (@DataAte IS NULL OR DATAABERTURA < DATEADD(day, 1, @DataAte))
    AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
    AND (@SearchPattern IS NULL OR (
        CAST(IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR JUSTIFICATIVA LIKE @SearchPattern
    ));

DECLARE @countMs int = DATEDIFF(millisecond, @t0, SYSDATETIME());
PRINT CONCAT('COUNT elapsed_ms=', @countMs);

SET @t0 = SYSDATETIME();

WITH REQUISICOES AS
(
    SELECT
        'AUMENTO_QUADRO' AS TIPO_REQUISICAO,
        R.CODCOLREQUISICAO,
        R.IDREQ,
        R.JUSTIFICATIVA,
        R.DATAABERTURA,
        R.DATAPREVISTA,
        R.DATACONCLUSAO,
        R.DATACANCELAMENTO,
        R.CODSTATUS,
        R.CODCOLREQUISITANTE,
        R.CHAPAREQUISITANTE,
        R.CODATENDIMENTO,
        R.CODLOCAL,
        CAST(NULL AS VARCHAR(20)) AS TIPOREQPAI,
        CAST(NULL AS INT) AS IDREQPAI,
        CAST(NULL AS VARCHAR(30)) AS CHAPA_FUNCIONARIO,
        CAST(NULL AS VARCHAR(30)) AS CHAPA_SUBSTITUTO,
        R.NUMVAGAS,
        R.CODFILIAL,
        R.CODSECAO,
        R.CODFUNCAO,
        R.VLRSALARIO,
        R.CODCCUSTO,
        R.RECCREATEDBY,
        R.RECCREATEDON,
        R.RECMODIFIEDBY,
        R.RECMODIFIEDON
    FROM VREQAUMENTOQUADRO R
        WHERE (@Tipo IS NULL OR @Tipo = 'AUMENTO_QUADRO')
        AND (@DataDe IS NULL OR R.DATAABERTURA >= @DataDe)
        AND (@DataAte IS NULL OR R.DATAABERTURA < DATEADD(day, 1, @DataAte))
        AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(R.CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
        AND (@SearchPattern IS NULL OR (CAST(R.IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR R.JUSTIFICATIVA LIKE @SearchPattern))
    UNION ALL
    SELECT
        'SUBSTITUICAO',
        R.CODCOLREQUISICAO,
        R.IDREQ,
        R.JUSTIFICATIVA,
        R.DATAABERTURA,
        R.DATAPREVISTA,
        R.DATACONCLUSAO,
        R.DATACANCELAMENTO,
        R.CODSTATUS,
        R.CODCOLREQUISITANTE,
        R.CHAPAREQUISITANTE,
        R.CODATENDIMENTO,
        R.CODLOCAL,
        R.TIPOREQPAI,
        R.IDREQPAI,
        CAST(NULL AS VARCHAR(30)),
        R.CHAPASUBSTITUTO,
        CAST(NULL AS INT),
        R.CODFILIAL,
        R.CODSECAO,
        R.CODFUNCAO,
        R.VLRSALARIO,
        R.CODCCUSTO,
        R.RECCREATEDBY,
        R.RECCREATEDON,
        R.RECMODIFIEDBY,
        R.RECMODIFIEDON
    FROM VREQSUBSTITUICAO R
        WHERE (@Tipo IS NULL OR @Tipo = 'SUBSTITUICAO')
        AND (@DataDe IS NULL OR R.DATAABERTURA >= @DataDe)
        AND (@DataAte IS NULL OR R.DATAABERTURA < DATEADD(day, 1, @DataAte))
        AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(R.CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
        AND (@SearchPattern IS NULL OR (CAST(R.IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR R.JUSTIFICATIVA LIKE @SearchPattern))
    UNION ALL
    SELECT
        'DESLIGAMENTO',
        R.CODCOLREQUISICAO,
        R.IDREQ,
        R.JUSTIFICATIVA,
        R.DATAABERTURA,
        R.DATAPREVISTA,
        R.DATACONCLUSAO,
        R.DATACANCELAMENTO,
        R.CODSTATUS,
        R.CODCOLREQUISITANTE,
        R.CHAPAREQUISITANTE,
        R.CODATENDIMENTO,
        R.CODLOCAL,
        CAST(NULL AS VARCHAR(20)),
        CAST(NULL AS INT),
        R.CHAPA,
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS INT),
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS VARCHAR(30)),
        CAST(NULL AS DECIMAL(18,2)),
        R.CODCCUSTO,
        R.RECCREATEDBY,
        R.RECCREATEDON,
        R.RECMODIFIEDBY,
        R.RECMODIFIEDON
    FROM VREQDESLIGAMENTO R
        WHERE (@Tipo IS NULL OR @Tipo = 'DESLIGAMENTO')
        AND (@DataDe IS NULL OR R.DATAABERTURA >= @DataDe)
        AND (@DataAte IS NULL OR R.DATAABERTURA < DATEADD(day, 1, @DataAte))
        AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(R.CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
        AND (@SearchPattern IS NULL OR (CAST(R.IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR R.JUSTIFICATIVA LIKE @SearchPattern))
),
Base AS (
    SELECT
        Q.TIPO_REQUISICAO,
        Q.CODCOLREQUISICAO,
        Q.IDREQ,
        Q.JUSTIFICATIVA,
        Q.DATAABERTURA,
        Q.DATAPREVISTA,
        Q.DATACONCLUSAO,
        Q.DATACANCELAMENTO,
        Q.CODSTATUS,
        S.DESCRICAO AS STATUS_DESCRICAO,
        S.PODEALTERAR AS STATUS_PERMITE_ALTERAR,
        Q.CODCOLREQUISITANTE,
        Q.CHAPAREQUISITANTE,
        FREQ.NOME AS NOME_REQUISITANTE,
        Q.CODATENDIMENTO,
        Q.CODLOCAL,
        HEXT.ASSUNTOOC AS ATENDIMENTO_ASSUNTO,
        Q.TIPOREQPAI,
        Q.IDREQPAI,
        Q.CHAPA_FUNCIONARIO,
        FFUNC.NOME AS NOME_FUNCIONARIO_ENVOLVIDO,
        Q.CHAPA_SUBSTITUTO,
        FSUB.NOME AS NOME_FUNCIONARIO_SUBSTITUTO,
        Q.NUMVAGAS,
        Q.CODFILIAL,
        Q.CODSECAO,
        Q.CODFUNCAO,
        FUN.NOME AS NOME_FUNCAO,
        FUN.DESCRICAO AS DESCRICAO_FUNCAO,
        Q.VLRSALARIO,
        Q.CODCCUSTO,
        Q.RECCREATEDBY,
        Q.RECCREATEDON,
        Q.RECMODIFIEDBY,
        Q.RECMODIFIEDON
    FROM REQUISICOES Q
    LEFT JOIN VREQSTATUS S ON S.CODINTERNO = Q.CODSTATUS
    LEFT JOIN PFUNC FREQ ON FREQ.CODCOLIGADA = Q.CODCOLREQUISITANTE AND FREQ.CHAPA = Q.CHAPAREQUISITANTE
    LEFT JOIN PFUNC FFUNC ON FFUNC.CODCOLIGADA = Q.CODCOLREQUISICAO AND FFUNC.CHAPA = Q.CHAPA_FUNCIONARIO
    LEFT JOIN PFUNC FSUB ON FSUB.CODCOLIGADA = Q.CODCOLREQUISICAO AND FSUB.CHAPA = Q.CHAPA_SUBSTITUTO
    LEFT JOIN PFUNCAO FUN ON FUN.CODCOLIGADA = Q.CODCOLREQUISICAO AND FUN.CODIGO = Q.CODFUNCAO
    LEFT JOIN HATENDIMENTOBASE HEXT ON HEXT.CODCOLIGADA = Q.CODCOLREQUISICAO AND HEXT.CODLOCAL = Q.CODLOCAL AND HEXT.CODATENDIMENTO = Q.CODATENDIMENTO
)
SELECT
    TIPO_REQUISICAO,
    IDREQ,
    CODSTATUS,
    CONVERT(varchar(10), DATAABERTURA, 120) AS DATAABERTURA
FROM Base
WHERE
    (@Tipo IS NULL OR TIPO_REQUISICAO = @Tipo)
    AND (@DataDe IS NULL OR DATAABERTURA >= @DataDe)
    AND (@DataAte IS NULL OR DATAABERTURA < DATEADD(day, 1, @DataAte))
    AND (@CodStatusCsv IS NULL OR CHARINDEX(',' + CAST(CODSTATUS AS VARCHAR(20)) + ',', @CodStatusCsv) > 0)
    AND (@SearchPattern IS NULL OR (
        CAST(IDREQ AS VARCHAR(20)) LIKE @SearchPattern OR JUSTIFICATIVA LIKE @SearchPattern
    ))
ORDER BY DATAABERTURA DESC, IDREQ DESC
OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY;

DECLARE @pageMs int = DATEDIFF(millisecond, @t0, SYSDATETIME());
PRINT CONCAT('PAGE elapsed_ms=', @pageMs);
