namespace RhPortal.Api.Domain.Enums;

public enum TipoDocumento : short
{
    RG = 0,
    CPF = 1,
    CNH = 2,
    TituloEleitor = 3,
    Reservista = 4,
    ComprovanteResidencia = 5,
    CertidaoNascimentoCasamento = 6,
    PisPasep = 7,
    Outro = 8,
    CarteiraTrabalhoCTPS = 9,
    DeclaracaoUniaoEstavel = 10,
    RGFilho = 11,
    CertidaoNascimentoFilho = 12,
    CarteiraVacinacaoFilho = 13,
    ComprovanteBancario = 14,
    Foto3x4 = 15,
    Escolaridade = 16,
    ExameMedico = 24,
    ComprovanteVacinaCovid = 25,
    CartaBoasVindas = 26,
    PrintValidacaoCep = 27,
    PrintConsultaCpfReceita = 28,
    CpfFilho = 29,
    FrequenciaEscolarFilho = 30,
    RgCpfConjuge = 31,
    // PJ
    CNPJ = 20,
    ContratoSocialMEI = 21,
    ContaBancariaPJ = 22,
    CertidoesNegativas = 23,
}
