WITH CENTROCUSTO (
   INSTANCIA
  ,FKCODCOLIGADA
  ,PKCODCCUSTO
  ,CODCCUSTOPAI
  ,[Data de Alteracao RECNO]
  ,CODCCUSTO
  ,DESCRICAO
) AS (
  SELECT
     INSTANCIA = <<INSTANCIA>>
    ,FKCODCOLIGADA = CONVERT(VARCHAR, PCCUSTO.CODCOLIGADA)
    ,PKCODCCUSTO = CONVERT(VARCHAR, PCCUSTO.CODCOLIGADA ) + '_' + ISNULL(CONVERT(VARCHAR, PCCUSTO.CODCCUSTO), 'N/A')
    ,CODCCUSTOPAI = DBO.FUNC_RETORNANIVELPAI(PCCUSTO.CODCCUSTO, '.', '_')
    ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PCCUSTO.RECMODIFIEDON, 112 ), '19000101')
    ,CODCCUSTO = PCCUSTO.CODCCUSTO
    ,DESCRICAO = ISNULL(PCCUSTO.NOME, 'N/A')
FROM
  PCCUSTO WITH (NOLOCK)
WHERE
  PCCUSTO.ATIVO = 'T'
)
SELECT DISTINCT
   NIVEL11.INSTANCIA
  ,NIVEL11.FKCODCOLIGADA
  ,NIVEL11.PKCODCCUSTO
  ,NIVEL11.[Data de Alteracao RECNO]
  ,NIVEL11.CODCCUSTO AS CODCCUSTO11
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
     OR NIVEL6.CODCCUSTO IS NULL
     OR NIVEL5.CODCCUSTO IS NULL
     OR NIVEL4.CODCCUSTO IS NULL
     OR NIVEL3.CODCCUSTO IS NULL
     OR NIVEL2.CODCCUSTO IS NULL
     OR NIVEL1.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   ELSE NIVEL10.CODCCUSTO
   END AS CODCCUSTO10
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
     OR NIVEL6.CODCCUSTO IS NULL
     OR NIVEL5.CODCCUSTO IS NULL
     OR NIVEL4.CODCCUSTO IS NULL
     OR NIVEL3.CODCCUSTO IS NULL
     OR NIVEL2.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   ELSE NIVEL9.CODCCUSTO
   END AS CODCCUSTO9
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
     OR NIVEL6.CODCCUSTO IS NULL
     OR NIVEL5.CODCCUSTO IS NULL
     OR NIVEL4.CODCCUSTO IS NULL
     OR NIVEL3.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   ELSE NIVEL8.CODCCUSTO
   END AS CODCCUSTO8
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
     OR NIVEL6.CODCCUSTO IS NULL
     OR NIVEL5.CODCCUSTO IS NULL
     OR NIVEL4.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   ELSE NIVEL7.CODCCUSTO
   END AS CODCCUSTO7
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
     OR NIVEL6.CODCCUSTO IS NULL
     OR NIVEL5.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL4.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL7.CODCCUSTO
   ELSE NIVEL6.CODCCUSTO
   END AS CODCCUSTO6
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
     OR NIVEL6.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL5.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL4.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL7.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL6.CODCCUSTO
   ELSE NIVEL5.CODCCUSTO
   END AS CODCCUSTO5
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
     OR NIVEL7.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL6.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL5.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL4.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL7.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL6.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL5.CODCCUSTO
   ELSE NIVEL4.CODCCUSTO
   END AS CODCCUSTO4
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
     OR NIVEL8.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL7.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL6.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL5.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   WHEN NIVEL4.CODCCUSTO IS NULL THEN NIVEL7.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL6.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL5.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL4.CODCCUSTO
   ELSE NIVEL3.CODCCUSTO
   END AS CODCCUSTO3
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL
     OR NIVEL9.CODCCUSTO IS NULL
   THEN NIVEL11.CODCCUSTO
   WHEN NIVEL8.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL7.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL6.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   WHEN NIVEL5.CODCCUSTO IS NULL THEN NIVEL7.CODCCUSTO
   WHEN NIVEL4.CODCCUSTO IS NULL THEN NIVEL6.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL5.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL4.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL3.CODCCUSTO
   ELSE NIVEL2.CODCCUSTO
   END AS CODCCUSTO2
  ,CASE
   WHEN NIVEL10.CODCCUSTO IS NULL THEN NIVEL11.CODCCUSTO
   WHEN NIVEL9.CODCCUSTO IS NULL THEN NIVEL10.CODCCUSTO
   WHEN NIVEL8.CODCCUSTO IS NULL THEN NIVEL9.CODCCUSTO
   WHEN NIVEL7.CODCCUSTO IS NULL THEN NIVEL8.CODCCUSTO
   WHEN NIVEL6.CODCCUSTO IS NULL THEN NIVEL7.CODCCUSTO
   WHEN NIVEL5.CODCCUSTO IS NULL THEN NIVEL6.CODCCUSTO
   WHEN NIVEL4.CODCCUSTO IS NULL THEN NIVEL5.CODCCUSTO
   WHEN NIVEL3.CODCCUSTO IS NULL THEN NIVEL4.CODCCUSTO
   WHEN NIVEL2.CODCCUSTO IS NULL THEN NIVEL3.CODCCUSTO
   WHEN NIVEL1.CODCCUSTO IS NULL THEN NIVEL2.CODCCUSTO
   ELSE NIVEL1.CODCCUSTO
   END AS CODCCUSTO1
  
  /* DESCRIÇÃO/NOME DOS CENTROS DE CUSTOS */
  
  ,NIVEL11.DESCRICAO AS DESCRICAO11
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
     OR NIVEL6.DESCRICAO IS NULL
     OR NIVEL5.DESCRICAO IS NULL
     OR NIVEL4.DESCRICAO IS NULL
     OR NIVEL3.DESCRICAO IS NULL
     OR NIVEL2.DESCRICAO IS NULL
     OR NIVEL1.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   ELSE NIVEL10.DESCRICAO
   END AS DESCRICAO10
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
     OR NIVEL6.DESCRICAO IS NULL
     OR NIVEL5.DESCRICAO IS NULL
     OR NIVEL4.DESCRICAO IS NULL
     OR NIVEL3.DESCRICAO IS NULL
     OR NIVEL2.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   ELSE NIVEL9.DESCRICAO
   END AS DESCRICAO9
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
     OR NIVEL6.DESCRICAO IS NULL
     OR NIVEL5.DESCRICAO IS NULL
     OR NIVEL4.DESCRICAO IS NULL
     OR NIVEL3.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   ELSE NIVEL8.DESCRICAO
   END AS DESCRICAO8
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
     OR NIVEL6.DESCRICAO IS NULL
     OR NIVEL5.DESCRICAO IS NULL
     OR NIVEL4.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   ELSE NIVEL7.DESCRICAO
   END AS DESCRICAO7
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
     OR NIVEL6.DESCRICAO IS NULL
     OR NIVEL5.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL4.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL7.DESCRICAO
   ELSE NIVEL6.DESCRICAO
   END AS DESCRICAO6
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
     OR NIVEL6.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL5.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL4.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL7.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL6.DESCRICAO
   ELSE NIVEL5.DESCRICAO
   END AS DESCRICAO5
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
     OR NIVEL7.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL6.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL5.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL4.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL7.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL6.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL5.DESCRICAO
   ELSE NIVEL4.DESCRICAO
   END AS DESCRICAO4
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
     OR NIVEL8.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL7.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL6.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL5.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   WHEN NIVEL4.DESCRICAO IS NULL THEN NIVEL7.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL6.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL5.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL4.DESCRICAO
   ELSE NIVEL3.DESCRICAO
   END AS DESCRICAO3
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL
     OR NIVEL9.DESCRICAO IS NULL
   THEN NIVEL11.DESCRICAO
   WHEN NIVEL8.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL7.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL6.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   WHEN NIVEL5.DESCRICAO IS NULL THEN NIVEL7.DESCRICAO
   WHEN NIVEL4.DESCRICAO IS NULL THEN NIVEL6.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL5.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL4.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL3.DESCRICAO
   ELSE NIVEL2.DESCRICAO
   END AS DESCRICAO2
  ,CASE
   WHEN NIVEL10.DESCRICAO IS NULL THEN NIVEL11.DESCRICAO
   WHEN NIVEL9.DESCRICAO IS NULL THEN NIVEL10.DESCRICAO
   WHEN NIVEL8.DESCRICAO IS NULL THEN NIVEL9.DESCRICAO
   WHEN NIVEL7.DESCRICAO IS NULL THEN NIVEL8.DESCRICAO
   WHEN NIVEL6.DESCRICAO IS NULL THEN NIVEL7.DESCRICAO
   WHEN NIVEL5.DESCRICAO IS NULL THEN NIVEL6.DESCRICAO
   WHEN NIVEL4.DESCRICAO IS NULL THEN NIVEL5.DESCRICAO
   WHEN NIVEL3.DESCRICAO IS NULL THEN NIVEL4.DESCRICAO
   WHEN NIVEL2.DESCRICAO IS NULL THEN NIVEL3.DESCRICAO
   WHEN NIVEL1.DESCRICAO IS NULL THEN NIVEL2.DESCRICAO
   ELSE NIVEL1.DESCRICAO
   END AS DESCRICAO1
FROM
  CENTROCUSTO NIVEL11 WITH (NOLOCK)
  LEFT JOIN CENTROCUSTO NIVEL10 WITH (NOLOCK) ON
      NIVEL11.CODCCUSTOPAI = NIVEL10.CODCCUSTO
  AND NIVEL10.CODCCUSTO <> NIVEL10.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL9 WITH (NOLOCK) ON
      NIVEL10.CODCCUSTOPAI = NIVEL9.CODCCUSTO
  AND NIVEL9.CODCCUSTO <> NIVEL9.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL8 WITH (NOLOCK) ON
      NIVEL9.CODCCUSTOPAI = NIVEL8.CODCCUSTO
  AND NIVEL8.CODCCUSTO <> NIVEL8.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL7 WITH (NOLOCK) ON
      NIVEL8.CODCCUSTOPAI = NIVEL7.CODCCUSTO
  AND NIVEL7.CODCCUSTO <> NIVEL7.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL6 WITH (NOLOCK) ON
      NIVEL7.CODCCUSTOPAI = NIVEL6.CODCCUSTO
  AND NIVEL6.CODCCUSTO <> NIVEL6.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL5 WITH (NOLOCK) ON
      NIVEL6.CODCCUSTOPAI = NIVEL5.CODCCUSTO
  AND NIVEL5.CODCCUSTO <> NIVEL5.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL4 WITH (NOLOCK) ON
      NIVEL5.CODCCUSTOPAI = NIVEL4.CODCCUSTO
  AND NIVEL4.CODCCUSTO <> NIVEL4.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL3 WITH (NOLOCK) ON
      NIVEL4.CODCCUSTOPAI = NIVEL3.CODCCUSTO
  AND NIVEL3.CODCCUSTO <> NIVEL3.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL2 WITH (NOLOCK) ON
      NIVEL3.CODCCUSTOPAI = NIVEL2.CODCCUSTO
  AND NIVEL2.CODCCUSTO <> NIVEL2.CODCCUSTOPAI
  LEFT JOIN CENTROCUSTO NIVEL1 WITH (NOLOCK) ON
      NIVEL2.CODCCUSTOPAI = NIVEL1.CODCCUSTO
  AND NIVEL1.CODCCUSTO <> NIVEL1.CODCCUSTOPAI

UNION

SELECT DISTINCT
   <<INSTANCIA>> AS INSTANCIA
  ,CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) AS FKCODCOLIGADA
  ,CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A' AS PKCODCCUSTO
  ,null AS [Data de Alteracao RECNO]
  ,'N/A' AS CODCCUSTO11
  ,'N/A' AS CODCCUSTO10
  ,'N/A' AS CODCCUSTO09
  ,'N/A' AS CODCCUSTO08
  ,'N/A' AS CODCCUSTO07
  ,'N/A' AS CODCCUSTO06
  ,'N/A' AS CODCCUSTO05
  ,'N/A' AS CODCCUSTO04
  ,'N/A' AS CODCCUSTO03
  ,'N/A' AS CODCCUSTO02
  ,'N/A' AS CODCCUSTO01
  ,'N/A' AS DESCRICAO11
  ,'N/A' AS DESCRICAO10
  ,'N/A' AS DESCRICAO09
  ,'N/A' AS DESCRICAO08
  ,'N/A' AS DESCRICAO07
  ,'N/A' AS DESCRICAO06
  ,'N/A' AS DESCRICAO05
  ,'N/A' AS DESCRICAO04
  ,'N/A' AS DESCRICAO03
  ,'N/A' AS DESCRICAO02
  ,'N/A' AS DESCRICAO01
FROM
  GCOLIGADA WITH (NOLOCK)
;