SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GDEPTO.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, GDEPTO.CODCOLIGADA) + '_' + CONVERT(VARCHAR, GDEPTO.CODFILIAL)
  ,PKCODDEPARTAMENTO = CONVERT(VARCHAR, GDEPTO.CODCOLIGADA) + '_' + CONVERT(VARCHAR, GDEPTO.CODFILIAL ) + '_' + CONVERT(VARCHAR, GDEPTO.CODDEPARTAMENTO)
  ,[Codigo do Departamento] = CONVERT(VARCHAR, GDEPTO.CODDEPARTAMENTO)
  ,[Nome do Departamento] = GDEPTO.NOME
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GDEPTO.RECMODIFIEDON, 112), '19000101')
FROM
  GDEPTO WITH (NOLOCK)

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + CONVERT( VARCHAR, GFILIAL.CODFILIAL)
  ,PKCODDEPARTAMENTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + CONVERT( VARCHAR, GFILIAL.CODFILIAL) + '_' + 'N/A'
  ,[Codigo do Departamento] = 'N/A'
  ,[Nome do Departamento] = 'N/A'
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GCOLIGADA.RECMODIFIEDON, 112), '19000101')
FROM
  GCOLIGADA WITH (NOLOCK)
  INNER JOIN GFILIAL WITH (NOLOCK) ON
  GCOLIGADA.CODCOLIGADA = GFILIAL.CODCOLIGADA

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + 'N/A'
  ,PKCODDEPARTAMENTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + 'N/A' + '_' + 'N/A'
  ,[Codigo do Departamento] = 'N/A'
  ,[Nome do Departamento] = 'N/A'
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GCOLIGADA.RECMODIFIEDON, 112), '19000101')
FROM
  GCOLIGADA WITH (NOLOCK)
;