SELECT
   INSTANCIA = <<INSTANCIA>>
  ,PKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,[Codigo da Empresa] = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,[Nome Fantasia Empresa] = UPPER(CONVERT(VARCHAR(255), GCOLIGADA.NOMEFANTASIA))
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GCOLIGADA.RECMODIFIEDON, 112), '19000101')
  ,PAIS = UPPER(CONVERT(VARCHAR(255), GCOLIGADA.PAIS))
  ,ESTADO = UPPER(CONVERT(VARCHAR(255), GCOLIGADA.ESTADO))
  ,CIDADE = UPPER(CONVERT(VARCHAR(255), GCOLIGADA.CIDADE))
FROM
  GCOLIGADA WITH (NOLOCK)

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,PKCODCOLIGADA = 'N/A'
  ,[Codigo da Empresa] = 'N/A'
  ,[Nome Fantasia Empresa] = 'N/A'
  ,[Data de Alteracao RECNO] = null
  ,PAIS = 'N/A'
  ,ESTADO = 'N/A'
  ,CIDADE = 'N/A'
;