SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PEVENTO.CODCOLIGADA)
  ,PKCODEVENTO = CONVERT(VARCHAR, PEVENTO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PEVENTO.CODIGO), 'N/A')
  ,[Codigo do Evento] = CONVERT(VARCHAR, PEVENTO.CODIGO)
  ,[Descricao do Evento] = ISNULL(UPPER(CONVERT(VARCHAR(255), PEVENTO.DESCRICAO)), 'N/A')
  ,[Codigo da Rubrica] = ISNULL(UPPER(PEVENTO.CODRUBRICA), 'N/A')
  ,[Descricao da Rubrica] = ISNULL(UPPER(PRUBRICA.DESCRICAO), 'N/A')
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PEVENTO.RECMODIFIEDON, 112), '19000101')
  ,[Codigo da Natureza da Rubrica] = ISNULL(PEVENTO.NATRUBRICA, 'N/A')
  ,[Descricao da Natureza da Rubrica] = ISNULL(PCODNATRUBRICA.DESCRICAO, 'N/A')
FROM
  PEVENTO WITH (NOLOCK)
  LEFT JOIN PRUBRICA WITH (NOLOCK) ON
      PEVENTO.CODCOLIGADA = PRUBRICA.CODCOLIGADA
  AND PEVENTO.CODRUBRICA = PRUBRICA.CODINTERNO
  LEFT JOIN PCODNATRUBRICA WITH (NOLOCK) ON
      PEVENTO.NATRUBRICA = PCODNATRUBRICA.CODINTERNO

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,PKCODEVENTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + 'N/A'
  ,[Codigo do Evento] = 'N/A'
  ,[Descricao do Evento] = 'N/A'
  ,[Codigo da Rubrica] = 'N/A'
  ,[Descricao da Rubrica] = 'N/A'
  ,[Data de Alteracao RECNO] = null
  ,[Codigo da Natureza da Rubrica] = 'N/A'
  ,[Descricao da Natureza da Rubrica] = 'N/A'
FROM
  GCOLIGADA WITH (NOLOCK)
;