SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GFILIAL.CODCOLIGADA)
  ,PKCODFILIAL = CONVERT(VARCHAR, GFILIAL.CODCOLIGADA) + '_' + CONVERT(VARCHAR, GFILIAL.CODFILIAL)
  ,[Codigo da Filial] = CONVERT(VARCHAR, GFILIAL.CODFILIAL)
  ,[Nome Fantasia Filial] = UPPER(CONVERT(VARCHAR(255), GFILIAL.NOMEFANTASIA))
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GFILIAL.RECMODIFIEDON, 112), '19000101')
  ,PAIS = UPPER(CONVERT(VARCHAR(255), GFILIAL.PAIS))
  ,ESTADO = UPPER(CONVERT(VARCHAR(255), GFILIAL.ESTADO))
  ,CIDADE = UPPER(CONVERT(VARCHAR(255), GFILIAL.CIDADE))
FROM
  GCOLIGADA WITH (NOLOCK)
  INNER JOIN GFILIAL WITH (NOLOCK) ON
  GCOLIGADA.CODCOLIGADA = GFILIAL.CODCOLIGADA

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,PKCODFILIAL = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + 'N/A'
  ,[Codigo da Filial] = 'N/A'
  ,[Nome Fantasia Filial] = 'N/A'
  ,[Data de Alteracao RECNO] = null
  ,PAIS = 'N/A'
  ,ESTADO = 'N/A'
  ,CIDADE = 'N/A'
FROM
  GCOLIGADA WITH (NOLOCK)
;