SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFUNC.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSECAO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSECAO), 'N/A')
  ,FKCODFUNCAO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFUNCAO), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCODSITUACAO = UPPER(ISNULL(CONVERT(VARCHAR(50), PFUNC.CODSITUACAO), 'N/A'))
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODFILIAL)  + '_' + CONVERT(VARCHAR, PSECAO.CODDEPTO), 'INDEFINDO')
  ,FKCODCUSTO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR(50), PFUNC.CODCCUSTO), 'N/A')
  ,FKPESSOA = UPPER(CONVERT(VARCHAR(50), PFUNC.CODPESSOA))
  ,FKCHAPA = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + UPPER(CONVERT(VARCHAR(25), PFUNC.CHAPA))
  ,[Deficiente Fisico] = CASE
    WHEN ISNULL(PPESSOA.DEFICIENTEFISICO, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.DEFICIENTEFISICO, 0) = 1 THEN 1
    END
  ,[Deficiente Auditivo] = CASE
    WHEN ISNULL(PPESSOA.DEFICIENTEAUDITIVO, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.DEFICIENTEAUDITIVO, 0) = 1 THEN 1
    END
  ,[Deficiente Fala] = CASE
    WHEN ISNULL(PPESSOA.DEFICIENTEFALA, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.DEFICIENTEFALA, 0) = 1 THEN 1
    END
   ,[Deficiente Visual] = CASE
    WHEN ISNULL(PPESSOA.DEFICIENTEVISUAL, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.DEFICIENTEVISUAL, 0) = 1 THEN 1
    END
  ,[Deficiente Mental] = CASE
    WHEN ISNULL(PPESSOA.DEFICIENTEMENTAL, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.DEFICIENTEMENTAL, 0) = 1 THEN 1
    END
  ,[Deficiente Intelectual] = CASE
    WHEN ISNULL(PPESSOA.DEFICIENTEINTELECTUAL, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.DEFICIENTEINTELECTUAL, 0) = 1 THEN 1
    END
  ,[Reabilitado] = CASE
    WHEN ISNULL(PPESSOA.BRPDH, 0) = 0 THEN 0
    WHEN ISNULL(PPESSOA.BRPDH, 0) = 1 THEN 1
    END
  ,[Cota PCD] = CASE
    WHEN ISNULL(PFUNC.COTAPCD, 0) = 0 THEN 0
    WHEN ISNULL(PFUNC.COTAPCD, 0) = 1 THEN 1
    END
FROM
  PFUNC WITH (NOLOCK)
  INNER JOIN PSECAO WITH (NOLOCK) ON
      PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA
  AND PFUNC.CODSECAO = PSECAO.CODIGO
  INNER JOIN PPESSOA WITH (NOLOCK) ON
  PFUNC.CODPESSOA = PPESSOA.CODIGO

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODSECAO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODFUNCAO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODSINDICATO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODSITUACAO = 'N/A'
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A_N/A'
  ,FKCODCUSTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKPESSOA = 'N/A'
  ,FKCHAPA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,[Deficiente Fisico] = 0
  ,[Deficiente Auditivo] = 0
  ,[Deficiente Fala] = 0
  ,[Deficiente Visual] = 0
  ,[Deficiente Mental] = 0
  ,[Deficiente Intelectual] = 0
  ,[Reabilitado] = 0
  ,[Cota PCD] = 0
FROM
  GCOLIGADA WITH (NOLOCK)
;