SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFUNCAO.CODCOLIGADA)
  ,PKCODFUNCAO = CONVERT(VARCHAR, PFUNCAO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNCAO.CODIGO), 'N/A')
  ,FKCODCARGO = CONVERT(VARCHAR, PFUNCAO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNCAO.CARGO), 'N/A')
  ,[Codigo da Funcao] = CONVERT(VARCHAR, PFUNCAO.CODIGO)
  ,[Nome da Funcao] = ISNULL(UPPER(CONVERT(VARCHAR(255), PFUNCAO.NOME)), 'N/A')
  ,[CBO da Funcao] = ISNULL(CONVERT(VARCHAR, PFUNCAO.CBO), 'N/A')
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFUNCAO.RECMODIFIEDON, 112), '19000101')
FROM
  PFUNCAO WITH (NOLOCK)
  LEFT JOIN PCARGO WITH (NOLOCK) ON
      PFUNCAO.CODCOLIGADA = PCARGO.CODCOLIGADA
  AND PFUNCAO.CARGO = PCARGO.CODIGO

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,PKCODFUNCAO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODCARGO = 'N/A'
  ,[Codigo da Funcao] = 'N/A'
  ,[Nome da Funcao] = 'N/A'
  ,[CBO da Funcao] = 'N/A'
  ,[Data de Alteracao RECNO] = null
FROM
  GCOLIGADA WITH (NOLOCK)
;