SELECT
   INSTANCIA = <<INSTANCIA>>
  ,SEC.CODCOLIGADA
  ,SEC.CODIGO CODSECAO
  ,CHEFE.CODCOLSUBST COLIGADACHEFE
  ,CONVERT(VARCHAR, CHEFE.CODCOLSUBST) + '_' + CHEFE.CHAPASUBST CHAPA
FROM
  PSECAO SEC WITH (NOLOCK)
INNER JOIN PSUBSTCHEFE CHEFE WITH (NOLOCK) ON
      SEC.CODCOLIGADA = CHEFE.CODCOLIGADA
  AND SUBSTRING(SEC.CODIGO, 1, 20) = CHEFE.CODSECAO
WHERE
  /* LEN(SEC.CODIGO) = 27
  AND */  DATAFIM IS NULL
  AND SEC.SECAODESATIVADA = 0
;
