SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PSECAO.CODCOLIGADA)
  ,PKCODSECAO = CONVERT(VARCHAR, PSECAO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODIGO), 'N/A')
  ,[Codigo da Secao] = UPPER(CONVERT(VARCHAR, PSECAO.CODIGO))
  ,[Descricao da Secao] = UPPER(CONVERT(VARCHAR, PSECAO.DESCRICAO))
  ,[Descricao da Secao PPP] = UPPER(CONVERT(VARCHAR(255), PSECAO.DESCRICAOPPP))
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PSECAO.RECMODIFIEDON, 112), '19000101')
FROM
  PSECAO WITH (NOLOCK)

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,PKCODSECAO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + 'N/A'
  ,[Codigo da Secao] = 'N/A'
  ,[Descricao da Secao] = 'N/A'
  ,[Descricao da Secao PPP] = 'N/A'
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GCOLIGADA.RECMODIFIEDON, 112), '19000101')
FROM
  GCOLIGADA WITH (NOLOCK)
;