SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PSINDIC.CODCOLIGADA)
  ,PKCODSINDICATO = CONVERT(VARCHAR, PSINDIC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PSINDIC.CODIGO), 'N/A')
  ,[Codigo do Sindicato] = CONVERT(VARCHAR, PSINDIC.CODIGO)
  ,[Nome do Sindicado] = ISNULL(UPPER(CONVERT(VARCHAR(255), PSINDIC.NOME ) ), 'N/A')
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PSINDIC.RECMODIFIEDON, 112), '19000101')
FROM
  PSINDIC WITH (NOLOCK)

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,PKCODSINDICATO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_' + 'N/A'
  ,[Codigo do Sindicato] = 'N/A'
  ,[Nome do Sindicado] = 'N/A'
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), GCOLIGADA.RECMODIFIEDON, 112), '19000101')
FROM
  GCOLIGADA WITH (NOLOCK)
;