SELECT
   INSTANCIA = <<INSTANCIA>>
  ,PKCODSITUACAO = UPPER(PCODSITUACAO.CODINTERNO)
  ,[Descricao da Situacao] = UPPER(CONVERT(VARCHAR(255), PCODSITUACAO.DESCRICAO))
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PCODSITUACAO.RECMODIFIEDON, 112), '19000101')
FROM
  PCODSITUACAO WITH (NOLOCK)

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,PKCODSITUACAO = 'N/A'
  ,[Descricao da Situacao] = 'N/A'
  ,[Data de Alteracao RECNO] = NULL
;