using System.ComponentModel.DataAnnotations;
using RhPortal.Api.Domain.Enums;
using RHPortal.Api.Domain.Enums;

namespace RhPortal.Api.Contracts.Vagas;

public sealed record VagaCreateRequest(
    [Required, MaxLength(160)] string Titulo,
    [Required] VagaStatus Status,
    [MaxLength(40)] string? Codigo,
    VagaAreaTime? AreaTime,
    VagaModalidade? Modalidade,
    VagaSenioridade? Senioridade,
    int QuantidadeVagas,
    VagaTipoContratacao? TipoContratacao,
    int MatchMinimoPercentual,
    VagaWeightsRequest? Weights,
    string? MatchingFiltrosRaw,
    string? DescricaoInterna,
    [MaxLength(40)] string? CodigoInterno,
    [MaxLength(20)] string? CodigoCbo,
    VagaMotivoAbertura? MotivoAbertura,
    VagaOrcamentoAprovado? OrcamentoAprovado,
    [MaxLength(120)] string? GestorRequisitante,
    [MaxLength(120)] string? RecrutadorResponsavel,
    VagaPrioridade? Prioridade,
    string? ResumoPitch,
    string? TagsResponsabilidadesRaw,
    string? TagsKeywordsRaw,
    bool Confidencial,
    bool AceitaPcd,
    bool Urgente,
    VagaGeneroPreferencia? GeneroPreferencia,
    bool VagaAfirmativa,
    bool LinguagemInclusiva,
    [MaxLength(120)] string? PublicoAfirmativo,
    string? ObservacoesPcd,
    [MaxLength(160)] string? ProjetoNome,
    [MaxLength(160)] string? ProjetoClienteAreaImpactada,
    [MaxLength(80)] string? ProjetoPrazoPrevisto,
    string? ProjetoDescricao,
    VagaRegimeJornada? Regime,
    int? CargaSemanalHoras,
    VagaEscalaTrabalho? Escala,
    string? EscalaTrabalhoRaw,
    TimeOnly? HoraEntrada,
    TimeOnly? HoraSaida,
    TimeSpan? Intervalo,
    [MaxLength(12)] string? Cep,
    [MaxLength(160)] string? Logradouro,
    [MaxLength(20)] string? Numero,
    [MaxLength(120)] string? Bairro,
    [MaxLength(120)] string? Cidade,
    [MaxLength(2)] string? Uf,
    [MaxLength(200)] string? PoliticaTrabalho,
    [MaxLength(200)] string? ObservacoesDeslocamento,
    VagaMoeda? Moeda,
    decimal? SalarioMinimo,
    decimal? SalarioMaximo,
    VagaRemuneracaoPeriodicidade? Periodicidade,
    VagaBonusTipo? BonusTipo,
    decimal? BonusPercentual,
    [MaxLength(240)] string? ObservacoesRemuneracao,
    VagaEscolaridade? Escolaridade,
    VagaFormacaoArea? FormacaoArea,
    int? ExperienciaMinimaAnos,
    string? TagsStackRaw,
    string? TagsIdiomasRaw,
    string? Diferenciais,
    string? ObservacoesProcesso,
    VagaPublicacaoVisibilidade? Visibilidade,
    DateOnly? DataInicio,
    DateOnly? DataEncerramento,
    bool CanalLinkedIn,
    bool CanalSiteCarreiras,
    bool CanalIndicacao,
    bool CanalPortaisEmprego,
    string? DescricaoPublica,
    bool LgpdSolicitarConsentimentoExplicito,
    bool LgpdCompartilharCurriculoInternamente,
    bool LgpdRetencaoAtiva,
    int? LgpdRetencaoMeses,
    bool ExigeCnh,
    bool DisponibilidadeParaViagens,
    bool ChecagemAntecedentes,
    int? SlaDiasMetaFechamento,
    [MaxLength(200)] string? NomeEngessado,
    Guid? JobPositionId,
    Guid? CategoriaSalarialId,
    Guid? CentroCustoId,
    Guid? TurnoId,
    Guid? UnidadeLotacaoId,
    Guid? EixoVagaId,
    /// <summary>FK p/ DescricaoCargo (template DNALIO consumido pelo MatchingService).</summary>
    Guid? DescricaoCargoId,
    /// <summary>Pesos calibrados por vaga (soma esperada=100). Sessão 31.8.</summary>
    int? PesoCompetencia,
    int? PesoExperiencia,
    int? PesoFormacao,
    int? PesoLocalidade,
    int? PesoIdioma,
    int? PesoConhecimentoTecnico,
    int? PesoVivenciaEspecifica,
    /// <summary>Distância máxima (km) p/ score de localidade. Null = usa default 50.</summary>
    int? LocalidadeMaxDistanciaKm,
    bool TravarFaixaSalarial,
    IReadOnlyList<VagaBeneficioRequest>? Beneficios,
    IReadOnlyList<VagaRequisitoRequest>? Requisitos,
    IReadOnlyList<VagaEtapaRequest>? Etapas,
    IReadOnlyList<VagaPerguntaRequest>? PerguntasTriagem,
    /// <summary>
    /// (Atribuição manual de vaga — 2026-04-26) Vincula a vaga a um usuário com role Recrutador.
    /// Quando preenchido por Admin/RH, sobrescreve auto-atribuição. Quando null e o usuário logado
    /// é Recrutador, o backend auto-atribui ao próprio. Use o endpoint dedicado
    /// <c>PATCH /api/vagas/{id}/recrutador</c> para atribuição em fluxo separado.
    /// </summary>
    Guid? RecrutadorResponsavelUserId = null
);

public sealed record UpdateVagaMatchingFiltrosRequest(string? MatchingFiltrosRaw);

/// <summary>
/// Atribui (ou desatribui, com null) uma vaga a um usuário recrutador.
/// Endpoint <c>PATCH /api/vagas/{id}/recrutador</c>. Permitido apenas para Admin/RH.
/// (Feature "Atribuição de Vaga a Recrutador" — 2026-04-26.)
/// </summary>
public sealed record AssignRecrutadorRequest(Guid? RecrutadorResponsavelUserId);

public sealed record AprovarAlcadaSalarialRequest(
    [property: MaxLength(1000)] string? Justificativa,
    [property: MaxLength(500)] string? ObservacaoAprovador
);

public sealed record ChangeVagaStatusRequest([Required] VagaStatus Status);

public sealed record VagaUpdateRequest(
    [Required, MaxLength(160)] string Titulo,
    [Required] VagaStatus Status,
    [MaxLength(40)] string? Codigo,
    VagaAreaTime? AreaTime,
    VagaModalidade? Modalidade,
    VagaSenioridade? Senioridade,
    int QuantidadeVagas,
    VagaTipoContratacao? TipoContratacao,
    int MatchMinimoPercentual,
    VagaWeightsRequest? Weights,
    string? MatchingFiltrosRaw,
    string? DescricaoInterna,
    [MaxLength(40)] string? CodigoInterno,
    [MaxLength(20)] string? CodigoCbo,
    VagaMotivoAbertura? MotivoAbertura,
    VagaOrcamentoAprovado? OrcamentoAprovado,
    [MaxLength(120)] string? GestorRequisitante,
    [MaxLength(120)] string? RecrutadorResponsavel,
    VagaPrioridade? Prioridade,
    string? ResumoPitch,
    string? TagsResponsabilidadesRaw,
    string? TagsKeywordsRaw,
    bool Confidencial,
    bool AceitaPcd,
    bool Urgente,
    VagaGeneroPreferencia? GeneroPreferencia,
    bool VagaAfirmativa,
    bool LinguagemInclusiva,
    [MaxLength(120)] string? PublicoAfirmativo,
    string? ObservacoesPcd,
    [MaxLength(160)] string? ProjetoNome,
    [MaxLength(160)] string? ProjetoClienteAreaImpactada,
    [MaxLength(80)] string? ProjetoPrazoPrevisto,
    string? ProjetoDescricao,
    VagaRegimeJornada? Regime,
    int? CargaSemanalHoras,
    VagaEscalaTrabalho? Escala,
    string? EscalaTrabalhoRaw,
    TimeOnly? HoraEntrada,
    TimeOnly? HoraSaida,
    TimeSpan? Intervalo,
    [MaxLength(12)] string? Cep,
    [MaxLength(160)] string? Logradouro,
    [MaxLength(20)] string? Numero,
    [MaxLength(120)] string? Bairro,
    [MaxLength(120)] string? Cidade,
    [MaxLength(2)] string? Uf,
    [MaxLength(200)] string? PoliticaTrabalho,
    [MaxLength(200)] string? ObservacoesDeslocamento,
    VagaMoeda? Moeda,
    decimal? SalarioMinimo,
    decimal? SalarioMaximo,
    VagaRemuneracaoPeriodicidade? Periodicidade,
    VagaBonusTipo? BonusTipo,
    decimal? BonusPercentual,
    [MaxLength(240)] string? ObservacoesRemuneracao,
    VagaEscolaridade? Escolaridade,
    VagaFormacaoArea? FormacaoArea,
    int? ExperienciaMinimaAnos,
    string? TagsStackRaw,
    string? TagsIdiomasRaw,
    string? Diferenciais,
    string? ObservacoesProcesso,
    VagaPublicacaoVisibilidade? Visibilidade,
    DateOnly? DataInicio,
    DateOnly? DataEncerramento,
    bool CanalLinkedIn,
    bool CanalSiteCarreiras,
    bool CanalIndicacao,
    bool CanalPortaisEmprego,
    string? DescricaoPublica,
    bool LgpdSolicitarConsentimentoExplicito,
    bool LgpdCompartilharCurriculoInternamente,
    bool LgpdRetencaoAtiva,
    int? LgpdRetencaoMeses,
    bool ExigeCnh,
    bool DisponibilidadeParaViagens,
    bool ChecagemAntecedentes,
    int? SlaDiasMetaFechamento,
    [MaxLength(200)] string? NomeEngessado,
    Guid? JobPositionId,
    Guid? CategoriaSalarialId,
    Guid? CentroCustoId,
    Guid? TurnoId,
    Guid? UnidadeLotacaoId,
    Guid? EixoVagaId,
    /// <summary>FK p/ DescricaoCargo (template DNALIO consumido pelo MatchingService).</summary>
    Guid? DescricaoCargoId,
    /// <summary>Pesos calibrados por vaga (soma esperada=100). Sessão 31.8.</summary>
    int? PesoCompetencia,
    int? PesoExperiencia,
    int? PesoFormacao,
    int? PesoLocalidade,
    int? PesoIdioma,
    int? PesoConhecimentoTecnico,
    int? PesoVivenciaEspecifica,
    /// <summary>Distância máxima (km) p/ score de localidade. Null = usa default 50.</summary>
    int? LocalidadeMaxDistanciaKm,
    bool TravarFaixaSalarial,
    IReadOnlyList<VagaBeneficioRequest>? Beneficios,
    IReadOnlyList<VagaRequisitoRequest>? Requisitos,
    IReadOnlyList<VagaEtapaRequest>? Etapas,
    IReadOnlyList<VagaPerguntaRequest>? PerguntasTriagem,
    /// <summary>(Atribuição manual de vaga — 2026-04-26) Idem VagaCreateRequest.</summary>
    Guid? RecrutadorResponsavelUserId = null
);

public sealed record VagaResponse(
    Guid Id,
    string? Codigo,
    string Titulo,
    VagaAreaTime? AreaTime,
    VagaModalidade? Modalidade,
    VagaStatus Status,
    VagaSenioridade? Senioridade,
    int QuantidadeVagas,
    VagaTipoContratacao? TipoContratacao,
    int MatchMinimoPercentual,
    VagaWeightsResponse Weights,
    string? MatchingFiltrosRaw,
    string? MatchingFiltrosOriginaisRaw,
    string? DescricaoInterna,
    string? CodigoInterno,
    string? CodigoCbo,
    VagaMotivoAbertura? MotivoAbertura,
    VagaOrcamentoAprovado? OrcamentoAprovado,
    string? GestorRequisitante,
    string? RecrutadorResponsavel,
    Guid? RecrutadorResponsavelUserId,
    VagaPrioridade? Prioridade,
    string? ResumoPitch,
    string? TagsResponsabilidadesRaw,
    string? TagsKeywordsRaw,
    bool Confidencial,
    bool AceitaPcd,
    bool Urgente,
    VagaGeneroPreferencia? GeneroPreferencia,
    bool VagaAfirmativa,
    bool LinguagemInclusiva,
    string? PublicoAfirmativo,
    string? ObservacoesPcd,
    string? ProjetoNome,
    string? ProjetoClienteAreaImpactada,
    string? ProjetoPrazoPrevisto,
    string? ProjetoDescricao,
    VagaRegimeJornada? Regime,
    int? CargaSemanalHoras,
    VagaEscalaTrabalho? Escala,
    string? EscalaTrabalhoRaw,
    TimeOnly? HoraEntrada,
    TimeOnly? HoraSaida,
    TimeSpan? Intervalo,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Bairro,
    string? Cidade,
    string? Uf,
    string? PoliticaTrabalho,
    string? ObservacoesDeslocamento,
    VagaMoeda? Moeda,
    decimal? SalarioMinimo,
    decimal? SalarioMaximo,
    VagaRemuneracaoPeriodicidade? Periodicidade,
    VagaBonusTipo? BonusTipo,
    decimal? BonusPercentual,
    string? ObservacoesRemuneracao,
    VagaEscolaridade? Escolaridade,
    VagaFormacaoArea? FormacaoArea,
    int? ExperienciaMinimaAnos,
    string? TagsStackRaw,
    string? TagsIdiomasRaw,
    string? Diferenciais,
    string? ObservacoesProcesso,
    VagaPublicacaoVisibilidade? Visibilidade,
    DateOnly? DataInicio,
    DateOnly? DataEncerramento,
    DateTimeOffset? DataAbertura,
    int? SlaDiasMetaFechamento,
    bool CanalLinkedIn,
    bool CanalSiteCarreiras,
    bool CanalIndicacao,
    bool CanalPortaisEmprego,
    string? DescricaoPublica,
    bool LgpdSolicitarConsentimentoExplicito,
    bool LgpdCompartilharCurriculoInternamente,
    bool LgpdRetencaoAtiva,
    int? LgpdRetencaoMeses,
    bool ExigeCnh,
    bool DisponibilidadeParaViagens,
    bool ChecagemAntecedentes,
    string? NomeEngessado,
    Guid? JobPositionId,
    string? JobPositionCode,
    string? JobPositionName,
    Guid? CategoriaSalarialId,
    string? CategoriaSalarialCode,
    string? CategoriaSalarialDescription,
    Guid? CentroCustoId,
    string? CentroCustoCode,
    string? CentroCustoDescription,
    Guid? TurnoId,
    string? TurnoCode,
    string? TurnoDescription,
    Guid? UnidadeLotacaoId,
    string? UnidadeLotacaoCode,
    string? UnidadeLotacaoDescription,
    Guid? EixoVagaId,
    string? EixoVagaCode,
    string? EixoVagaName,
    int? EixoVagaSlaDiasMetaFechamento,
    int? SlaEfetivoDias,
    // Sessão 31.8 — DescricaoCargo + pesos calibrados + dist max
    Guid? DescricaoCargoId,
    string? DescricaoCargoCode,
    string? DescricaoCargoTitle,
    int PesoCompetencia,
    int PesoExperiencia,
    int PesoFormacao,
    int PesoLocalidade,
    int PesoIdioma,
    int PesoConhecimentoTecnico,
    int PesoVivenciaEspecifica,
    int? LocalidadeMaxDistanciaKm,
    bool TravarFaixaSalarial,
    Guid? AlcadaSalarialAprovadaPorUserId,
    DateTimeOffset? AlcadaSalarialAprovadaEmUtc,
    string? AlcadaSalarialJustificativa,
    string? AlcadaSalarialObservacaoAprovador,
    decimal? FaixaSalarialMinimo,
    decimal? FaixaSalarialMaximo,
    bool FaixaSalarialViolada,
    IReadOnlyList<VagaBeneficioResponse> Beneficios,
    IReadOnlyList<VagaRequisitoResponse> Requisitos,
    IReadOnlyList<VagaEtapaResponse> Etapas,
    IReadOnlyList<VagaPerguntaResponse> PerguntasTriagem,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    string? SolicitanteNome,
    string? AprovadorNome,
    DateTimeOffset? DataAprovacao,
    int HeadcountAutorizado,
    int HeadcountOcupado,
    bool IsEstrutural,
    int HeadcountProvisorio,
    bool AlertaHCProvVencido,
    int HeadcountPendente,
    Guid? SolicitacaoPendenteDecisaoId,
    TipoDecisaoHeadcount? DecisaoRH,
    string? DecisaoRHRevisadoPorNome,
    DateTimeOffset? DecisaoRHEmUtc,
    int? DecisaoRHPrazoMeses,
    DateTimeOffset? HeadcountProvisorioExpiresAtUtc
);

public sealed record VagaBeneficioRequest(
    int Ordem,
    VagaBeneficioTipo Tipo,
    decimal? Valor,
    VagaBeneficioRecorrencia Recorrencia,
    bool Obrigatorio,
    string? Observacoes
);

public sealed record VagaRequisitoRequest(
    int Ordem,
    [MaxLength(80)] string? Categoria,
    [Required, MaxLength(180)] string Nome,
    VagaPeso Peso,
    bool Obrigatorio,
    int? AnosMinimos,
    VagaRequisitoNivel? Nivel,
    VagaRequisitoAvaliacao? Avaliacao,
    IReadOnlyList<string>? Sinonimos,
    [MaxLength(240)] string? Observacoes
);

public sealed record VagaEtapaRequest(
    int Ordem,
    [Required, MaxLength(160)] string Nome,
    VagaEtapaResponsavel Responsavel,
    VagaEtapaModo Modo,
    int? SlaDias,
    [MaxLength(240)] string? DescricaoInstrucoes
);

public sealed record VagaPerguntaRequest(
    int Ordem,
    [Required, MaxLength(220)] string Texto,
    VagaPerguntaTipo Tipo,
    VagaPeso Peso,
    bool Obrigatoria,
    bool Knockout,
    string? OpcoesRaw
);

public sealed record VagaBeneficioResponse(
    Guid Id,
    int Ordem,
    VagaBeneficioTipo Tipo,
    decimal? Valor,
    VagaBeneficioRecorrencia Recorrencia,
    bool Obrigatorio,
    string? Observacoes,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaRequisitoResponse(
    Guid Id,
    int Ordem,
    string? Categoria,
    string Nome,
    VagaPeso Peso,
    bool Obrigatorio,
    int? AnosMinimos,
    VagaRequisitoNivel? Nivel,
    VagaRequisitoAvaliacao? Avaliacao,
    IReadOnlyList<string> Sinonimos,
    string? Observacoes,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaWeightsRequest(
    int Competencia,
    int Experiencia,
    int Formacao,
    int Localidade
);

public sealed record VagaWeightsResponse(
    int Competencia,
    int Experiencia,
    int Formacao,
    int Localidade
);

public sealed record VagaEtapaResponse(
    Guid Id,
    int Ordem,
    string Nome,
    VagaEtapaResponsavel Responsavel,
    VagaEtapaModo Modo,
    int? SlaDias,
    string? DescricaoInstrucoes,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaPerguntaResponse(
    Guid Id,
    int Ordem,
    string Texto,
    VagaPerguntaTipo Tipo,
    VagaPeso Peso,
    bool Obrigatoria,
    bool Knockout,
    string? OpcoesRaw,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaHistoricoEvent(
    string Acao,
    string? QuemFez,
    DateTimeOffset DataHora,
    Guid? EntidadeId,
    string? EntidadeTipo
);
