SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFUNC.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSECAO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSECAO), 'N/A')
  ,FKCODFUNCAO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFUNCAO), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCODSITUACAO = UPPER(ISNULL(CONVERT(VARCHAR(50), PFUNC.CODSITUACAO), 'N/A'))
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODFILIAL) + '_' + CONVERT(VARCHAR, PSECAO.CODDEPTO), 'N/A')
  ,FKCODCUSTO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR(50), PFUNC.CODCCUSTO), 'N/A')
  ,FKPESSOA = UPPER(CONVERT(VARCHAR(50), PFUNC.CODPESSOA))
  ,PKCHAPA = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + UPPER( CONVERT( VARCHAR(25), PFUNC.CHAPA))
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFHSTAFT.RECMODIFIEDON, 112), '19000101')
  ,[Data Inicio do Afastamento] = ISNULL(CONVERT(VARCHAR(10), PFHSTAFT.DTINICIO, 112), '19000101')
  ,[Data Final do Afastamento] = CONVERT(VARCHAR(10), PFHSTAFT.DTFINAL, 112)
  ,[Qtde Dias de Afastamento] = DATEDIFF(DAY, PFHSTAFT.DTINICIO, ISNULL(PFHSTAFT.DTFINAL, GETDATE()))
  ,[Qtde Horas de Afastamento] = DATEDIFF(DAY, PFHSTAFT.DTINICIO, ISNULL(PFHSTAFT.DTFINAL, GETDATE())) * 24
  ,[Tipo do Afastamento] = UPPER(PFHSTAFT.TIPO)
  ,[Descricao do Tipo] = UPPER(PCODAFAST.DESCRICAO)
  ,[Motivo do Afastamento] = UPPER(PFHSTAFT.MOTIVO)
  ,[Descricao do Motivo] = UPPER(PMUDSITUACAO.DESCRICAO)
  ,[CID] = UPPER(PFHSTAFT.CODCID)
FROM 
  PFHSTAFT WITH (NOLOCK)
  INNER JOIN PFUNC WITH (NOLOCK) ON
        PFHSTAFT.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND PFHSTAFT.CHAPA = PFUNC.CHAPA
  LEFT JOIN PSECAO WITH (NOLOCK) ON
        PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA
    AND PFUNC.CODSECAO = PSECAO.CODIGO
  INNER JOIN PCODAFAST WITH (NOLOCK) ON
    PFHSTAFT.TIPO = PCODAFAST.CODINTERNO
  INNER JOIN PMUDSITUACAO WITH (NOLOCK) ON
        PFHSTAFT.CODCOLIGADA = PMUDSITUACAO.CODCOLIGADA
    AND PFHSTAFT.MOTIVO = PMUDSITUACAO.CODINTERNO
WHERE
  CONVERT(VARCHAR(10), PFHSTAFT.DTINICIO, 112) BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;