SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSECAO = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA)  + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSEC.CODSECAO ), 'N/A')
  ,FKCODFUNCAO = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTFCO.CODFUNCAO ), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO ), 'N/A')
  ,FKCHAPA = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, ASALDOBANCOHOR.CHAPA ), 'N/A')
  ,FKCODSITUACAO = UPPER(ISNULL(CONVERT(VARCHAR(50), PFHSTSIT.NOVASITUACAO), 'N/A'))
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA) + '_' + CONVERT(VARCHAR, PFUNC.CODFILIAL) + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODDEPTO), 'N/A')
  ,FKCODCUSTO = CONVERT(VARCHAR, ASALDOBANCOHOR.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR(50), PSECAO.NROCENCUSTOCONT), 'N/A')
  ,[Data de Competencia Banco Horas] = CONVERT(VARCHAR(10), ASALDOBANCOHOR.DTBASE, 112)
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), ASALDOBANCOHOR.DTBASE, 112), '19000101')
  ,[Extra Anterior Banco Horas] = ASALDOBANCOHOR.EXTRAANT
  ,[Atraso Anterior Banco Horas] = ASALDOBANCOHOR.ATRASOANT
  ,[Falta Anterior Banco Horas] = ASALDOBANCOHOR.FALTAANT
  ,[Extra Atual Banco Horas] = ASALDOBANCOHOR.EXTRAATU
  ,[Atraso Atual Banco Horas] = ASALDOBANCOHOR.ATRASOATU
  ,[Falta Atual Banco Horas] = ASALDOBANCOHOR.FALTAATU
FROM
  (SELECT
     ASALDOBANCOHOR.*
    ,DATEADD(DAY, -1, DATEADD(MONTH, 1, CONVERT(DATE, CONVERT(VARCHAR(10), (APERFUN.ANOCOMP * 10000) + (APERFUN.MESCOMP * 100) + 1)))) AS DTBASE
  FROM
    ASALDOBANCOHOR WITH (NOLOCK)
    INNER JOIN APERFUN WITH (NOLOCK) ON
          ASALDOBANCOHOR.CODCOLIGADA = APERFUN.CODCOLIGADA
      AND ASALDOBANCOHOR.CHAPA = APERFUN.CHAPA
      AND ASALDOBANCOHOR.INICIOPER = APERFUN.INICIOPER
      AND ASALDOBANCOHOR.FIMPER = APERFUN.FIMPER
   WHERE (APERFUN.ANOCOMP > 0 OR APERFUN.MESCOMP > 0)
  ) ASALDOBANCOHOR
  INNER JOIN PFUNC WITH (NOLOCK) ON
        ASALDOBANCOHOR.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND ASALDOBANCOHOR.CHAPA = PFUNC.CHAPA
  LEFT JOIN PFHSTSEC WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = ASALDOBANCOHOR.CODCOLIGADA
    AND PFHSTSEC.CHAPA = ASALDOBANCOHOR.CHAPA
    AND PFHSTSEC.DTMUDANCA = (
      SELECT MAX(PFHSTSEC1.DTMUDANCA)
      FROM PFHSTSEC PFHSTSEC1 WITH (NOLOCK)
      WHERE PFHSTSEC1.CODCOLIGADA = ASALDOBANCOHOR.CODCOLIGADA
        AND PFHSTSEC1.CHAPA = ASALDOBANCOHOR.CHAPA
        AND PFHSTSEC1.DTMUDANCA < ASALDOBANCOHOR.DTBASE)
  LEFT JOIN PSECAO WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PSECAO.CODCOLIGADA
    AND PFHSTSEC.CODSECAO = PSECAO.CODIGO
  LEFT JOIN PFHSTFCO WITH (NOLOCK) ON
        PFHSTFCO.CODCOLIGADA = ASALDOBANCOHOR.CODCOLIGADA
    AND PFHSTFCO.CHAPA = ASALDOBANCOHOR.CHAPA
    AND PFHSTFCO.DTMUDANCA = (
      SELECT MAX(PFHSTFCO1.DTMUDANCA)
      FROM PFHSTFCO PFHSTFCO1 WITH (NOLOCK)
      WHERE PFHSTFCO1.CODCOLIGADA = ASALDOBANCOHOR.CODCOLIGADA
        AND PFHSTFCO1.CHAPA = ASALDOBANCOHOR.CHAPA
        AND PFHSTFCO1.DTMUDANCA < ASALDOBANCOHOR.DTBASE)
  LEFT JOIN PFHSTSIT WITH (NOLOCK) ON
        PFHSTSIT.CODCOLIGADA = ASALDOBANCOHOR.CODCOLIGADA
    AND PFHSTSIT.CHAPA = ASALDOBANCOHOR.CHAPA
    AND PFHSTSIT.DATAMUDANCA = (
      SELECT MAX(PFHSTSIT1.DATAMUDANCA)
      FROM PFHSTSIT PFHSTSIT1 WITH (NOLOCK)
      WHERE PFHSTSIT1.CODCOLIGADA = ASALDOBANCOHOR.CODCOLIGADA
        AND PFHSTSIT1.CHAPA = ASALDOBANCOHOR.CHAPA
        AND PFHSTSIT1.DATAMUDANCA < ASALDOBANCOHOR.DTBASE)
WHERE
  CONVERT(VARCHAR(10), ASALDOBANCOHOR.DTBASE, 112) BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;

