SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSECAO = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA)  + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSEC.CODSECAO), 'N/A')
  ,FKCODFUNCAO = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTFCO.CODFUNCAO), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCHAPA = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUFERIASVERBAS.CHAPA), 'N/A')
  ,FKCODEVENTO = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUFERIASVERBAS.CODEVENTO), 'N/A')
  ,FKCODSITUACAO = UPPER(ISNULL(CONVERT(VARCHAR(50), PFHSTSIT.NOVASITUACAO), 'N/A'))
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + CONVERT(VARCHAR, PFUNC.CODFILIAL)  + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODDEPTO), 'N/A')
  ,FKCODCUSTO = CONVERT(VARCHAR, PFUFERIASVERBAS.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR(50), PSECAO.NROCENCUSTOCONT), 'N/A')
  ,[Prov/Desc/Base Ferias] = CONVERT( VARCHAR(10), PEVENTO.PROVDESCBASE )
  ,[Data de Competencia Ferias] = CONVERT(VARCHAR(10), PFUFERIASVERBAS.DTBASE, 112)
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFUFERIASVERBAS.RECMODIFIEDON, 112), '19000101')
  ,[Data Inicio Ferias] = CONVERT(VARCHAR(10), PFUFERIASVERBAS.INICIOPERAQUIS, 112)
  ,[Data Termino Ferias] = CONVERT(VARCHAR(10), PFUFERIASVERBAS.FIMPERAQUIS, 112)
  ,[Valor Liquido Ferias] = PFUFERIASVERBAS.VALOR
  ,[Valor Provento Ferias] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'P' THEN PFUFERIASVERBAS.VALOR
    ELSE 0.00
    END
  ,[Horas Provento Ferias] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'P' THEN PFUFERIASVERBAS.HORA
    ELSE 0.00
    END
  ,[Valor Desconto Ferias] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'D' THEN PFUFERIASVERBAS.VALOR
    ELSE 0.00
    END
  ,[Horas Desconto Ferias] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'D' THEN PFUFERIASVERBAS.HORA
    ELSE 0.00
    END
  ,[Valor BaseCalc Ferias] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'B' THEN PFUFERIASVERBAS.VALOR
    ELSE 0.00
    END
  ,[Horas BaseCalc Ferias] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'B' THEN PFUFERIASVERBAS.HORA
    ELSE 0.00
    END
FROM (
  SELECT
     PFUFERIASVERBAS.*
    ,PFUFERIAS.INICIOPERAQUIS
    ,DATEADD(DAY, -1, DATEADD(MONTH, 1, CONVERT(DATE, CONVERT(VARCHAR(10), (YEAR(PFUFERIASVERBAS.DATAPAGTO) * 10000) + (MONTH(PFUFERIASVERBAS.DATAPAGTO) * 100) + 1)))) AS DTBASE
  FROM
    PFUFERIASVERBAS WITH (NOLOCK)
    INNER JOIN PFUFERIAS WITH (NOLOCK) ON
          PFUFERIASVERBAS.CODCOLIGADA = PFUFERIAS.CODCOLIGADA
      AND PFUFERIASVERBAS.CHAPA = PFUFERIAS.CHAPA
      AND PFUFERIASVERBAS.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS
  ) PFUFERIASVERBAS
  INNER JOIN PFUNC WITH (NOLOCK) ON
        PFUFERIASVERBAS.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND PFUFERIASVERBAS.CHAPA = PFUNC.CHAPA
  INNER JOIN PEVENTO WITH (NOLOCK) ON
        PFUFERIASVERBAS.CODCOLIGADA = PEVENTO.CODCOLIGADA
    AND PFUFERIASVERBAS.CODEVENTO = PEVENTO.CODIGO
  LEFT JOIN PFHSTSEC WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA
    AND PFHSTSEC.CHAPA = PFUFERIASVERBAS.CHAPA
    AND PFHSTSEC.DTMUDANCA = (
      SELECT MAX(PFHSTSEC1.DTMUDANCA)
      FROM PFHSTSEC PFHSTSEC1 WITH (NOLOCK)
      WHERE PFHSTSEC1.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA
        AND PFHSTSEC1.CHAPA = PFUFERIASVERBAS.CHAPA
        AND PFHSTSEC1.DTMUDANCA < PFUFERIASVERBAS.DTBASE)
  LEFT JOIN PSECAO WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PSECAO.CODCOLIGADA
    AND PFHSTSEC.CODSECAO = PSECAO.CODIGO
  LEFT JOIN PFHSTFCO WITH (NOLOCK) ON
        PFHSTFCO.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA
    AND PFHSTFCO.CHAPA = PFUFERIASVERBAS.CHAPA
    AND PFHSTFCO.DTMUDANCA = (
      SELECT MAX(PFHSTFCO1.DTMUDANCA)
      FROM PFHSTFCO PFHSTFCO1 WITH (NOLOCK)
      WHERE PFHSTFCO1.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA
        AND PFHSTFCO1.CHAPA = PFUFERIASVERBAS.CHAPA
        AND PFHSTFCO1.DTMUDANCA < PFUFERIASVERBAS.DTBASE)
  LEFT JOIN PFHSTSIT WITH (NOLOCK) ON
        PFHSTSIT.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA
    AND PFHSTSIT.CHAPA = PFUFERIASVERBAS.CHAPA
    AND PFHSTSIT.DATAMUDANCA = (
      SELECT MAX(PFHSTSIT1.DATAMUDANCA)
      FROM PFHSTSIT PFHSTSIT1 WITH (NOLOCK)
      WHERE PFHSTSIT1.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA
        AND PFHSTSIT1.CHAPA = PFUFERIASVERBAS.CHAPA
        AND PFHSTSIT1.DATAMUDANCA < PFUFERIASVERBAS.DTBASE)
WHERE
  CONVERT(VARCHAR(10), PFUFERIASVERBAS.RECMODIFIEDON, 112) BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;