SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSECAO = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA)  + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSEC.CODSECAO), 'N/A')
  ,FKCODFUNCAO = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTFCO.CODFUNCAO), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCHAPA = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA) + '_' + ISNULL( CONVERT(VARCHAR, PFFINANC.CHAPA), 'N/A')
  ,FKCODEVENTO = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA) + '_' + ISNULL( CONVERT(VARCHAR, PFFINANC.CODEVENTO ), 'N/A')
  ,FKCODSITUACAO = UPPER(ISNULL(CONVERT(VARCHAR(50), PFHSTSIT.NOVASITUACAO), 'N/A'))
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA ) + '_' + CONVERT(VARCHAR, PFUNC.CODFILIAL) + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODDEPTO), 'N/A')
  ,FKCODCUSTO = CONVERT(VARCHAR, PFFINANC.CODCOLIGADA ) + '_' + ISNULL(CONVERT(VARCHAR(50), PSECAO.NROCENCUSTOCONT), 'N/A')
  ,[Prov/Desc/Base Envelope] = CONVERT(VARCHAR(10), PEVENTO.PROVDESCBASE)
  ,[Data de Pagto Envelope] = CONVERT(VARCHAR(10), PFFINANC.DTPAGTO, 112)
  ,[Data de Competencia Envelope] = CONVERT(VARCHAR(10), PFFINANC.DTBASE, 112)
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFFINANC.RECMODIFIEDON, 112), '19000101')
  ,[Valor Liquido Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'P' THEN PFFINANC.VALOR
    WHEN PEVENTO.PROVDESCBASE  = 'D' THEN PFFINANC.VALOR
    END
  ,[Valor Provento Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'P' THEN +PFFINANC.VALOR
    ELSE 0.00
    END
  ,[Horas Provento Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'P' THEN PFFINANC.REF
    ELSE 0.00
    END
  ,[Valor Desconto Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'D' THEN PFFINANC.VALOR
    ELSE 0.00 END
  ,[Horas Desconto Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'D' THEN PFFINANC.REF
    ELSE 0.00
    END
  ,[Valor BaseCalc Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'B' THEN +PFFINANC.VALOR
    ELSE 0.00
    END
  ,[Horas BaseCalc Envelope] = CASE
    WHEN PEVENTO.PROVDESCBASE  = 'B' THEN PFFINANC.HORA
    ELSE 0.00
    END 
FROM (
  SELECT
     'MOVIMENTO' AS TIPO
    ,PFFINANC.CODCOLIGADA
    ,PFFINANC.CHAPA
    ,PFFINANC.ANOCOMP
    ,PFFINANC.MESCOMP
    ,PFFINANC.NROPERIODO
    ,PFFINANC.CODEVENTO
    ,PFFINANC.DTPAGTO
    ,PFFINANC.HORA
    ,PFFINANC.REF
    ,PFFINANC.VALOR
    ,PFFINANC.VALORORIGINAL
    ,PFFINANC.RECCREATEDON
    ,PFFINANC.RECMODIFIEDON
    ,DATEADD(DAY, -1, DATEADD(MONTH, 1, CONVERT(DATE, CONVERT(VARCHAR(10), (PFFINANC.ANOCOMP * 10000) + (PFFINANC.MESCOMP * 100) + 1)))) AS DTBASE
  FROM
    PFFINANC WITH (NOLOCK)
  
  UNION ALL
  
  SELECT
     'HISTORICO' AS TIPO
    ,PFFINANC.CODCOLIGADA
    ,PFFINANC.CHAPA
    ,PFFINANC.ANOCOMP
    ,PFFINANC.MESCOMP
    ,PFFINANC.NROPERIODO
    ,PFFINANC.CODEVENTO
    ,PFFINANC.DTPAGTO
    ,PFFINANC.HORA
    ,PFFINANC.REF
    ,PFFINANC.VALOR
    ,PFFINANC.VALORORIGINAL
    ,PFFINANC.RECCREATEDON
    ,PFFINANC.RECMODIFIEDON
    ,DATEADD(DAY, -1, DATEADD(MONTH, 1, CONVERT(DATE, CONVERT(VARCHAR(10), (PFFINANC.ANOCOMP * 10000 ) + (PFFINANC.MESCOMP * 100) + 1)))) AS DTBASE
  FROM
    PFFINANCCOMPL PFFINANC WITH (NOLOCK)
  ) PFFINANC
  INNER JOIN PFUNC WITH (NOLOCK) ON
        PFFINANC.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND PFFINANC.CHAPA = PFUNC.CHAPA
  INNER JOIN PEVENTO WITH (NOLOCK) ON
        PFFINANC.CODCOLIGADA = PEVENTO.CODCOLIGADA
    AND PFFINANC.CODEVENTO = PEVENTO.CODIGO
  LEFT JOIN PFHSTSEC WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PFFINANC.CODCOLIGADA
    AND PFHSTSEC.CHAPA = PFFINANC.CHAPA
    AND PFHSTSEC.DTMUDANCA = (
      SELECT MAX(PFHSTSEC1.DTMUDANCA)
      FROM PFHSTSEC PFHSTSEC1 WITH (NOLOCK)
      WHERE PFHSTSEC1.CODCOLIGADA = PFFINANC.CODCOLIGADA
        AND PFHSTSEC1.CHAPA = PFFINANC.CHAPA
        AND PFHSTSEC1.DTMUDANCA < PFFINANC.DTBASE)
  LEFT JOIN PSECAO WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PSECAO.CODCOLIGADA
    AND PFHSTSEC.CODSECAO = PSECAO.CODIGO
  LEFT JOIN PFHSTFCO WITH (NOLOCK) ON
        PFHSTFCO.CODCOLIGADA = PFFINANC.CODCOLIGADA
    AND PFHSTFCO.CHAPA = PFFINANC.CHAPA
    AND PFHSTFCO.DTMUDANCA = (
      SELECT MAX(PFHSTFCO1.DTMUDANCA)
      FROM PFHSTFCO PFHSTFCO1 WITH (NOLOCK)
      WHERE PFHSTFCO1.CODCOLIGADA = PFFINANC.CODCOLIGADA
        AND PFHSTFCO1.CHAPA = PFFINANC.CHAPA
        AND PFHSTFCO1.DTMUDANCA < PFFINANC.DTBASE)
  LEFT JOIN PFHSTSIT WITH (NOLOCK) ON
        PFHSTSIT.CODCOLIGADA = PFFINANC.CODCOLIGADA
    AND PFHSTSIT.CHAPA = PFFINANC.CHAPA
    AND PFHSTSIT.DATAMUDANCA = (
      SELECT MAX(PFHSTSIT1.DATAMUDANCA)
      FROM PFHSTSIT PFHSTSIT1 WITH (NOLOCK)
      WHERE PFHSTSIT1.CODCOLIGADA = PFFINANC.CODCOLIGADA
        AND PFHSTSIT1.CHAPA = PFFINANC.CHAPA
        AND PFHSTSIT1.DATAMUDANCA < PFFINANC.DTBASE)
WHERE
  PFFINANC.RECMODIFIEDON BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;