SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFHSTSAL.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFHSTSAL.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFHSTSAL.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCHAPA = CONVERT(VARCHAR, PFHSTSAL.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSAL.CHAPA), 'N/A')
  ,FKCODEVENTO = CONVERT(VARCHAR, PFHSTSAL.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSAL.CODEVENTO), 'N/A')
  ,[Codigo Motivo] = PFHSTSAL.MOTIVO
  ,[Descricao do Motivo] = UPPER(PMOTMUDSAL.DESCRICAO)
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFHSTSAL.RECMODIFIEDON, 112), '19000101')
  ,[Salario Historico] = PFHSTSAL.SALARIO
FROM
  PFHSTSAL WITH (NOLOCK)
  INNER JOIN PFUNC WITH (NOLOCK) ON
        PFHSTSAL.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND PFHSTSAL.CHAPA = PFUNC.CHAPA
  INNER JOIN PMOTMUDSAL WITH (NOLOCK) ON
        PFHSTSAL.CODCOLIGADA = PMOTMUDSAL.CODCOLIGADA
    AND PFHSTSAL.MOTIVO = PMOTMUDSAL.CODINTERNO
WHERE
  CONVERT(VARCHAR(10), PFHSTSAL.RECMODIFIEDON, 112) BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;
