SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFHSTFCO.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFHSTFCO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFHSTFCO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCHAPA = CONVERT(VARCHAR, PFHSTFCO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CHAPA), 'N/A')
  ,FKCODFUNCAOATUAL = CONVERT(VARCHAR, PFHSTFCO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTFCO.CODFUNCAO), 'N/A')
  ,FKCODFUNCAOANTERIOR = CONVERT(VARCHAR, PFHSTFCO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTFCO_.CODFUNCAO), 'N/A')
  ,[Descricao Mudanca Funcao] = CONVERT(VARCHAR(255), UPPER(PMOTMUDFUNCAO.DESCRICAO))
  ,[Tipo de Mudanca] = CASE
     WHEN PFHSTFCO_.CODFUNCAO IS NULL THEN 'MESMA FUNCAO'
     WHEN PFHSTFCO.CODFUNCAO <> PFHSTFCO_.CODFUNCAO THEN 'MUDOU A FUNCAO'
     END
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFHSTFCO.RECMODIFIEDON, 112), '19000101')
  ,[Data de Mudanca Funcao] = ISNULL(CONVERT(VARCHAR(10), PFHSTFCO.DTMUDANCA, 112), '19000101')
FROM
  PFHSTFCO WITH (NOLOCK)
  INNER JOIN PFUNC WITH (NOLOCK) ON
        PFHSTFCO.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND PFHSTFCO.CHAPA = PFUNC.CHAPA
  LEFT JOIN PFHSTFCO AS PFHSTFCO_ WITH (NOLOCK) ON
        PFHSTFCO_.CODCOLIGADA = PFHSTFCO.CODCOLIGADA
    AND PFHSTFCO_.CHAPA = PFHSTFCO.CHAPA
    AND PFHSTFCO_.DTMUDANCA = (
      SELECT MAX(PFHSTFCO__.DTMUDANCA)
      FROM PFHSTFCO AS PFHSTFCO__ WITH (NOLOCK)
      WHERE PFHSTFCO__.CODCOLIGADA = PFHSTFCO_.CODCOLIGADA
        AND PFHSTFCO__.CHAPA = PFHSTFCO_.CHAPA
        AND PFHSTFCO__.DTMUDANCA < PFHSTFCO.DTMUDANCA)
  INNER JOIN PMOTMUDFUNCAO WITH (NOLOCK) ON
        PFHSTFCO.CODCOLIGADA = PMOTMUDFUNCAO.CODCOLIGADA
    AND PFHSTFCO.MOTIVO = PMOTMUDFUNCAO.CODINTERNO
WHERE
  CONVERT(VARCHAR(10), PFHSTFCO.RECMODIFIEDON, 112) BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;
