SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFHSTSEC.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFHSTSEC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFHSTSEC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCHAPA = CONVERT(VARCHAR, PFHSTSEC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CHAPA), 'N/A')
  ,FKCODSECAOATUAL = CONVERT(VARCHAR, PFHSTSEC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSEC.CODSECAO), 'N/A')
  ,FKCODSECAOANTERIOR = CONVERT(VARCHAR, PFHSTSEC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFHSTSEC_.CODSECAO), 'N/A')
  ,[Descricao Mudanca Funcao] = CONVERT(VARCHAR(255), UPPER(PMOTMUDFUNCAO.DESCRICAO))
  ,[Tipo de Mudanca] = CASE
     WHEN PFHSTSEC_.CODSECAO IS NULL THEN 'MESMA SECAO'
     WHEN PFHSTSEC.CODSECAO <> PFHSTSEC_.CODSECAO THEN 'MUDOU A SECAO'
     END
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFHSTSEC.RECMODIFIEDON, 112), '19000101')
  ,[Data de Mudanca Funcao] = ISNULL(CONVERT(VARCHAR(10), PFHSTSEC.DTMUDANCA, 112), '19000101')
FROM
  PFHSTSEC WITH (NOLOCK)
  INNER JOIN PFUNC WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PFUNC.CODCOLIGADA
    AND PFHSTSEC.CHAPA = PFUNC.CHAPA
  LEFT JOIN PFHSTSEC AS PFHSTSEC_ WITH (NOLOCK) ON
        PFHSTSEC_.CODCOLIGADA = PFHSTSEC.CODCOLIGADA
    AND PFHSTSEC_.CHAPA = PFHSTSEC.CHAPA
    AND PFHSTSEC_.DTMUDANCA = (
      SELECT MAX(PFHSTSEC__.DTMUDANCA)
      FROM PFHSTSEC AS PFHSTSEC__ WITH (NOLOCK)
      WHERE PFHSTSEC__.CODCOLIGADA = PFHSTSEC_.CODCOLIGADA
        AND PFHSTSEC__.CHAPA = PFHSTSEC_.CHAPA
        AND PFHSTSEC__.DTMUDANCA < PFHSTSEC.DTMUDANCA)
  INNER JOIN PMOTMUDFUNCAO WITH (NOLOCK) ON
        PFHSTSEC.CODCOLIGADA = PMOTMUDFUNCAO.CODCOLIGADA
    AND PFHSTSEC.MOTIVO = PMOTMUDFUNCAO.CODINTERNO
WHERE
  CONVERT(VARCHAR(10), PFHSTSEC.RECMODIFIEDON, 112) BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
;
