// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RhPortal.Api.Infrastructure.Data;

#nullable disable

namespace RhPortal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411090000_AddNivelCargoIdToFuncionarios")]
    partial class AddNivelCargoIdToFuncionarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot managed by EF Core tooling — regenerate via: dotnet ef migrations add
        }
    }
}
